export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
export const ADD_TO_BAG = "ADD_TO_BAG";
